#!/bin/bash
# Run with:
# ./play production all
# ./play production webservers
# ./play production dbservers
# ./play production webservers --tags=pip

INVENTORY=$1
ROLE=${2:-"site"}

echo "Pulling vars from $PROJECTDIR"
echo "Configuring ..."
echo "inventory: ${INVENTORY}"
echo "role: ${ROLES}"

/usr/bin/env ansible-playbook --ask-sudo-pass --inventory-file=$INVENTORY "$(dirname $0)/playbook/${ROLE}.yml" --extra-vars="files=$PWD/deployment/files" "${@:3}"
